name: Release new version

on:
  push:
    branches:
      - main
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag name that the major tag will point to'
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}
permissions:
  contents: write

jobs:
  update_tag:
    name: Update the major tag to include the ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }} changes
    environment:
      name: releaseNewActionVersion
    runs-on: [self-hosted, Linux, small]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Release Tag
        id: tag
        run: |
          TAG_VERSION=$(git describe --tags --abbrev=0)
          git tag -a $TAG_VERSION -m "Release $TAG_VERSION"
          git push origin $TAG_VERSION

    #   - name: Update the ${{ env.TAG_NAME }} tag
    #     uses: actions/publish-action@v0.2.2
    #     with:
    #       source-tag: ${{ env.TAG_NAME }}
    #       slack-webhook: ${{ secrets.SLACK_WEBHOOK }}